name: build-go-binary

on:
  release:
    types: [created, published] # 表示在创建新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        goarch: [386, arm, amd64, arm64] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: darwin
          - goarch: 386
            goos: darwin
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.52
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23.2 # 可以指定编译使用的 Golang 版本
          binary_name: "dns-shift" # 可以指定二进制文件的名称
          extra_files: README.md dns-shift.yaml setup-cron.sh doc/* # 需要包含的额外文件
